### ISSUE TITLE
El estilo «descontrolado» en la wiki

### ISSUE THREAD

**Issue by cibersheep** [Baltasarq/txtpaws#2]
Hay varios párrafos en los que ¿lo bloques de código? no se reconocen correctamente y se ve el código html.

Ejemplo:

![imatge](https://cloud.githubusercontent.com/assets/6640041/24080223/ca777932-0c9a-11e7-8c93-706c592d84d8.png)

**Comment by Baltasarq** [comment]
Converted original HTML to markdown to avoid problems related to indention (interpreted as source code).

**Comment by cibersheep** [comment]
Excellent. Thanks! Now looks gorgeous again.
