### ISSUE TITLE
Can't compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by cibersheep** [Baltasarq/txtpaws#3]
Hello :)

Just for the record: I tried to compile txtpaws on Ubuntu 20.04 and I get this error.
```
make txtpaws
g++ -m32 -O2 -c txtpaws.cpp -otxtpaws.o
In file included from txtpaws.h:9,
                 from txtpaws.cpp:8:
/usr/include/c++/9/cstdio:41:10: fatal error: bits/c++config.h: File or directory doesn't exist
   41 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: txtpaws.o] Error 1
```

This is because `-m32` is specified. I guess 32 bits binary is required for other tools.
Workaround: 
- build for 64 bits `g++ -O2 -c txtpaws.cpp -otxtpaws.o`
- Install i386 arch: On Ubuntu `sudo apt-get install g++-multilib libc6-dev-i386`

**Comment by Baltasarq** [comment]
Thanks for the heads up!
I upgraded the source code so it compiles now for the C++ standard.
I actually don't remember exactly why I had to add -m32, something I needed for it to compile, but it is now gone for good.
